{% set name = "PyInstaller" %}
{% set version = "3.4" %}
{% set sha256 = "a5a6e04a66abfcf8761e89a2ebad937919c6be33a7b8963e1a961b55cb35986b" %}

package:
  name: {{ name.lower() }}
  version: {{ version }}

source:
  fn: PyInstaller-{{ version }}.tar.bz2
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-depend-bindepend-find-statically-linked-libraries.patch

build:
  number: 1
  entry_points:
    - pyinstaller = PyInstaller.__main__:run
    - pyi-archive_viewer = PyInstaller.utils.cliutils.archive_viewer:run
    - pyi-bindepend = PyInstaller.utils.cliutils.bindepend:run
    - pyi-grab_version = PyInstaller.utils.cliutils.grab_version:run
    - pyi-makespec = PyInstaller.utils.cliutils.makespec:run
    - pyi-set_version = PyInstaller.utils.cliutils.set_version:run
  script:
    - export LDFLAGS="${LDFLAGS} -L${PREFIX}/lib"               # [unix]
    - pushd bootloader
    - waf --prefix="${PREFIX}" --clang distclean all            # [osx]
    - waf --prefix="${PREFIX}" --gcc --no-lsb distclean all     # [linux]
    - waf --prefix="%LIBRARY_PREFIX%" distclean all             # [win]
    - popd
    - python setup.py install --single-version-externally-managed --record=record.txt
  preserve_egg_dir: True

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - setuptools
    - waf
    - zlib

  run:
    - python
    - setuptools
    - pefile >=2017.9.3  # [win]
    - pycrypto
    - pywin32  # [win]
    - pywin32-ctypes  # [win]
    - zlib
    - dis3  # [py27]
    - macholib >=1.8

test:
  imports:
    - PyInstaller

  commands:
    - pyinstaller --help
    - pyi-archive_viewer --help
    - pyi-bindepend --help
    - pyi-makespec --help
    # These are designed for Windows only.
    - pyi-grab_version --help     # [win]
    - pyi-set_version --help      # [win]

  files:
    - hello.py

about:
  home: http://www.pyinstaller.org
  license: GPL 2
  license_file: COPYING.txt
  summary: PyInstaller bundles a Python application and all its dependencies into a single package.

extra:
  recipe-maintainers:
    - jakirkham
    - nicoddemus
