{% set name = "pyinstaller" %}
{% set version = "4.4" %}
{% set sha256 = "af3ef0b9f265a2d3859357a25ab16743fbb6143c89fd7c3570cb84b8d24db0ba" %}

package:
  name: {{ name.lower() }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # Fixes compiler/linker errors when building on macos
    - 0001-Remove-custom-compiler-linker-flags-when-building-ma.patch

build:
  number: 0
  skip: true  # [py<35 or py>39]
  entry_points:
    - pyinstaller = PyInstaller.__main__:run
    - pyi-archive_viewer = PyInstaller.utils.cliutils.archive_viewer:run
    - pyi-bindepend = PyInstaller.utils.cliutils.bindepend:run
    - pyi-grab_version = PyInstaller.utils.cliutils.grab_version:run
    - pyi-makespec = PyInstaller.utils.cliutils.makespec:run
    - pyi-set_version = PyInstaller.utils.cliutils.set_version:run
  script:
    - export LDFLAGS="${LDFLAGS} -L${PREFIX}/lib"               # [unix]
    - export LDFLAGS="${LDFLAGS} -mmacosx-version-min=${MACOSX_DEPLOYMENT_TARGET}"  # [osx]
    # Remove the pre-compiled bootloaders (available in sdist)
    - rm -fr ${SRC_DIR}/PyInstaller/bootloader/{Darwin,Linux,Windows}-{64,32}bit  # [unix]
    - pushd bootloader
    - waf --prefix="${PREFIX}" --clang distclean all            # [osx]
    - waf --prefix="${PREFIX}" --gcc --no-lsb distclean all     # [linux]
    - waf --prefix="%LIBRARY_PREFIX%" distclean all             # [win]
    - popd
    - {{ PYTHON }} -m pip install . --no-deps -vv
  preserve_egg_dir: true

requirements:
  build:
    - {{ compiler("c") }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - pip
    - python
    - setuptools
  host:
    - pip
    - python
    - setuptools
    - waf
    - zlib

  run:
    - altgraph
    - python
    - pefile >=2017.9.3       # [win]
    - pywin32                 # [win]
    - pywin32-ctypes >=0.2.0  # [win]
    - macholib >=1.8
    - pyinstaller-hooks-contrib >=2020.6
    - setuptools  # due to pkg_resources import
    - importlib-metadata >=0.8  # [py<38]

test:
  imports:
    - PyInstaller

  commands:
    - pyinstaller --help
    - pyi-archive_viewer --help
    - pyi-bindepend --help
    - pyi-makespec --help
    # These are designed for Windows only.
    - pyi-grab_version --help     # [win]
    - pyi-set_version --help      # [win]

  files:
    - hello.py

about:
  home: http://www.pyinstaller.org
  # https://github.com/pyinstaller/pyinstaller/blob/v3.6/COPYING.txt#L11
  license: GPL-2.0-or-later WITH Bootloader-exception
  license_family: GPL
  license_file: COPYING.txt
  summary: PyInstaller bundles a Python application and all its dependencies into a single package.

extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
    - nicoddemus
    - nehaljwani
