build_platform:
  osx_arm64: osx_64
build_with_mambabuild: false
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: native
  linux_ppc64le: native
test_on_native_only: true
conda_build:
  pkg_format: '2'
