travis:
  secure:
    BINSTAR_TOKEN: TyYzMwSTXhazV8sHOYXsMe0P6IMaycK42AQDHtTWNXF1E+qXjpqJh2KOrgnubppHfLyAEFE2qZN4rECQEroarB7QPBCFSgdpgbWEdaclFT6su1YjBLdRHQ2UE7ftLIARv0PhFYvzAZBfsHRqn4T3MLwWzcM5UHS5I78MV5rJ92jE1HN1KGb715BtxBijvmxx3SgNcVH8FjtL1wjZHHdlm2Q2EgQsUX4EnWYwdpU1taGVbV5LAEosJ6IMM6SrJsrCFcIHtcVPmHa9kh+aAmlHiX4QtHM40WUP4IUgnC/++yFa2kk1Fju6IPXZddFksG5bZnpIF2D9dYFNPLbdl4QfC7hWTzTsaRNqmkppmkzcNJ7G6AYEBIVShZ3RVg/Rdt7zZtXcXgMeBjid7ZJR5CcQ6y4g840fNsN9nBkXkc2r06lbXENZnOs5bwVIEi7NUS2jW+9DsQO83rSn+GI2LhZYMAHL6Og0OyaSrYpx4hcJmnfkH3piwUK31eVYTLsbbvMa3pwC+I7+XhN6rpO5bPmOb94QpHt87QNafaAyjc0seZchWn6nBK+aa/rY9JoEPoGK6xDahqD5kPw/SHvJgUZ5+Py7cTCphqOO/wDFPQgQG72SQnRuhigRoSIriXiDQGqSdwcJfRMsGChYxqu0jcKmj+3cIXtLoZvcPE4mLR8ODHk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
